module.exports = {
    emailrequired:"Email is required",
    passwordrequired:"password is required",
    update:"Update successfully",
    alreadyemail:"Email already exist",
    emailotpnotmatch:"Email OTP not matched",
    usernotfound:"User Not found",
    usersnotfound:"Users Not found",
    invalidpassword:"Invalid Password!",
    loginsuccessfully:"Login Successfully",
    userfetch:"User Fetched",
    usersfetch:"Users Fetched",
    datanotfound:"data not found",
    profileupdate:"Profile update successfully",
    checkmail:"Please check the mail",
    wrong:"Something went wrong",
    delete:"Deleted Successfully",
    logout:"logout successfully",
    inactiveAcount:"Inactive Account",
    deletedAccount:"Deleted Account",
    NotokenProvided:"No token provided!",
    Unauthorized:"Unauthorized!",
    oldpassword:"Old password is required",
    newpassword:"New password is required",
    confirmpassword:"Confirm password is required",
    confirmpasswordnotmatch:"Your password and confirmation password do not match",
    oldpasswordiswrong:"Old password is wrong",
    changepasswordsuccess:"Password changed successfully",
    tokenrequired:"Token is required",
    invaildtoken:"Invaild token!",
    roleid:"Role id is required",
    platform:"Platform is required",
    namerequired:"name is required",
    emailformat:"Email format issue",
    useridrequired:"user id is required",
    profilestatusupdate:"Profile status changed successfully",
    useradded:"user added",
    emailalreadyExists:"Email already exits",
    phonelreadyExists:"Phone already exits",
    statusrequired:"Status is required",
    noaccessrole:"no access",
    idrequired:"id is required",
    statusupdate:"Status changed successfully",
    savedata:"Added successfully",
    updatedata:"Update successfully",
    listdata:"successfully",
    alreadyExists:"Already exits",
    notfound:"Not found",
    datafound:"Data found",
    titlerequired:"Title is required"
  };